<script setup lang="ts">
import { computed } from 'vue'
import { ArrowUpRight, ArrowRight, Plus, Users, ClipboardList, CheckCheck, Sparkles, GraduationCap, RefreshCw } from 'lucide-vue-next'
import type { User, Conversation, Assignment, TeachingStats } from '../shared/api'
import ActivityChart from '../shared/ActivityChart.vue'
const props = defineProps<{ user: User; records: Conversation[]; assignments: Assignment[]; stats: TeachingStats }>()
const emit = defineEmits<{ navigate: [page: string]; create: []; refresh: [] }>()
const published = computed(() => props.assignments.filter(a => a.status === 'published'))
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">TEACH WITH INSIGHT</div><h1>{{ user.name }}，今天也一起启发思考。</h1><p>连接课堂、练习与反馈，让每一次教学都有迹可循。</p></div><button class="primary-button" @click="emit('create')"><Plus :size="17"/> 新建作业</button></div>
  <section class="hero-banner teacher-hero"><div class="hero-copy"><span class="hero-tag"><Sparkles :size="14"/> 数伴 · 教学助手</span><h2>把更多时间，<br>留给<span>真正的启发。</span></h2><p>整理教学思路，发布课堂任务，查看学生的作答。</p><button class="primary-button" @click="emit('navigate', 'agent')">打开教学助手 <ArrowUpRight :size="18"/></button><small>教学建议为预设示例，使用前请自行复核</small></div><div class="teacher-art" aria-hidden="true"><div class="paper-card back"></div><div class="paper-card"><span>LESSON NOTES</span><h3>从「知道」<br>到「理解」</h3><div class="paper-line"></div><div class="paper-line short"></div><span class="paper-equation">Δy / Δx → f′(x)</span><GraduationCap :size="36"/></div><span class="art-star">✧</span></div></section>
  <div class="stats-grid"><div class="stat-card"><span class="stat-icon green"><Users :size="21"/></span><div><span>演示班级学生</span><strong>1<small>人</small></strong></div><span class="stat-detail">预设账号</span></div><div class="stat-card"><span class="stat-icon lilac"><ClipboardList :size="21"/></span><div><span>已发布作业</span><strong>{{ stats.published }}<small>份</small></strong></div></div><div class="stat-card"><span class="stat-icon peach"><CheckCheck :size="21"/></span><div><span>收到学生作答</span><strong>{{ stats.submitted }}<small>份</small></strong></div><span class="stat-detail">实际提交</span></div></div>
  <section class="panel review-overview"><div class="section-heading"><h3>反馈进度</h3><button class="subtle-link" @click="emit('refresh')"><RefreshCw :size="14"/> 刷新统计</button></div><div class="review-stats"><div><strong>{{ stats.pending }}</strong><span>待批改</span></div><div><strong>{{ stats.needs_improvement }}</strong><span>待改进</span></div><div><strong>{{ stats.completed }}</strong><span>教师确认完成</span></div></div><p class="muted small">仅统计未归档的已发布作业及最新作答，不推断知识掌握度。</p></section>
  <div class="dashboard-grid"><section class="panel"><div class="section-heading"><h3>最近发布的作业</h3><button class="subtle-link" @click="emit('navigate', 'assignments')">全部作业 <ArrowRight :size="15"/></button></div><div v-for="a in published.slice(0, 4)" :key="a.id" class="teacher-assignment"><span class="stat-icon green"><ClipboardList :size="21"/></span><div><h4>{{ a.title }}</h4><p>{{ a.topic }} · 截止 {{ a.due_date }}</p></div><span class="small-pill">{{ a.submissions?.length || 0 }} 份提交</span><button class="icon-button" :aria-label="'查看'+a.title" @click="emit('navigate', 'assignments')"><ArrowUpRight :size="19"/></button></div><div class="teaching-reminder"><h4>让反馈成为下一次教学的起点</h4><p>当前演示班级仅包含预设学生账号。可以查看实际提交并给出人工反馈；真实班级与 AI 学情诊断后续接入。</p><button class="subtle-link" @click="emit('navigate', 'students')">查看演示班级 <ArrowRight :size="15"/></button></div></section><aside><section class="panel activity-panel"><div class="section-heading"><h3>我的教学探索</h3><span class="muted small">近 7 天</span></div><ActivityChart :green="true" :dates="records.map(r => r.created_at)"/><p class="chart-caption">与教学助手的实际对话次数</p></section><div class="gentle-note"><Sparkles :size="19"/><p>一个好的问题，<br>往往比答案更有力量。</p></div></aside></div>
</template>
