<script setup lang="ts">
import { computed } from 'vue'
import { ArrowUpRight, ArrowRight, Plus, Users, ClipboardList, CheckCheck, Sparkles, GraduationCap, RefreshCw } from 'lucide-vue-next'
import type { User, Conversation, Assignment, TeachingStats, TeachingClass } from '../shared/api'
import ActivityChart from '../shared/ActivityChart.vue'
const props = defineProps<{ user: User; records: Conversation[]; assignments: Assignment[]; stats: TeachingStats; classes: TeachingClass[]; classId: string; loading: boolean }>()
const emit = defineEmits<{ navigate: [page: string]; create: []; refresh: []; filter: [classId: string] }>()
const published = computed(() => props.assignments.filter(a => a.status === 'published' && !a.class_archived))
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">TEACH WITH INSIGHT</div><h1>{{ user.name }}，今天也一起启发思考。</h1><p>连接课堂、练习与反馈，让每一次教学都有迹可循。</p></div><button class="primary-button" @click="emit('create')"><Plus :size="17"/> 新建作业</button></div>
  <section class="hero-banner teacher-hero"><div class="hero-copy"><span class="hero-tag"><Sparkles :size="14"/> 数伴 · 教学工作空间</span><h2>把更多时间，<br>留给<span>真正的启发。</span></h2><p>建好班级，发布课堂任务，让每一份作答得到反馈。</p><button class="primary-button" @click="emit('navigate', 'students')">{{ classes.length ? '管理我的班级' : '创建第一个班级' }} <ArrowUpRight :size="18"/></button><small>教学数据来自实际提交与教师反馈</small></div><div class="teacher-art" aria-hidden="true"><div class="paper-card back"></div><div class="paper-card"><span>LESSON NOTES</span><h3>从「知道」<br>到「理解」</h3><div class="paper-line"></div><div class="paper-line short"></div><span class="paper-equation">Δy / Δx → f′(x)</span><GraduationCap :size="36"/></div><span class="art-star">✧</span></div></section>
  <div class="panel work-toolbar dashboard-filter"><label for="overview-class">教学数据范围</label><select id="overview-class" :value="classId" :disabled="loading" @change="emit('filter', ($event.target as HTMLSelectElement).value)"><option value="">全部使用中的班级</option><option v-for="c in classes.filter(c => !c.archived)" :key="c.id" :value="c.id">{{ c.name }}</option></select><button class="subtle-link" :disabled="loading" @click="emit('refresh')"><RefreshCw :size="14"/> {{ loading ? '更新中…' : '刷新统计' }}</button></div>
  <div class="stats-grid teaching-stats" :aria-busy="loading"><div class="stat-card"><span class="stat-icon green"><Users :size="21"/></span><div><span>在班学生</span><strong>{{ stats.students }}<small>人</small></strong></div><span class="stat-detail">{{ stats.classes }} 个班级</span></div><div class="stat-card"><span class="stat-icon lilac"><ClipboardList :size="21"/></span><div><span>已发布作业</span><strong>{{ stats.published }}<small>份</small></strong></div><span class="stat-detail">应交 {{ stats.expected }} 份</span></div><div class="stat-card"><span class="stat-icon peach"><CheckCheck :size="21"/></span><div><span>收到学生作答</span><strong>{{ stats.submitted }}<small>份</small></strong></div><span class="stat-detail">未交 {{ stats.unsubmitted }} 份</span></div></div>
  <section class="panel review-overview"><div class="section-heading"><h3>反馈进度</h3><button class="subtle-link" @click="emit('refresh')"><RefreshCw :size="14"/> 刷新统计</button></div><div class="review-stats"><div><strong>{{ stats.pending }}</strong><span>待批改</span></div><div><strong>{{ stats.needs_improvement }}</strong><span>待改进</span></div><div><strong>{{ stats.completed }}</strong><span>教师确认完成</span></div></div><p class="muted small">统计使用中班级的已发布作业与最新作答；应交份数按发布时的接收名单计算。不推断知识掌握度。</p></section>
  <div class="dashboard-grid"><section class="panel"><div class="section-heading"><h3>最近发布的作业</h3><button class="subtle-link" @click="emit('navigate', 'assignments')">全部作业 <ArrowRight :size="15"/></button></div><div v-for="a in published.slice(0, 4)" :key="a.id" class="teacher-assignment"><span class="stat-icon green"><ClipboardList :size="21"/></span><div><h4>{{ a.title }}</h4><p>{{ a.class_name }} · 截止 {{ a.due_date }}</p></div><span class="small-pill">{{ a.submissions?.length || 0 }} / {{ a.recipient_count }} 份提交</span><button class="icon-button" :aria-label="'查看'+a.title" @click="emit('navigate', 'assignments')"><ArrowUpRight :size="19"/></button></div><p v-if="!published.length && !loading" class="empty-small">{{ !stats.classes ? '还没有使用中的班级。先创建班级并添加学生。' : !stats.students ? '班级已经就绪，添加学生后就能发布作业。' : '还没有发布的作业。从题库选题或新建草稿开始。' }}</p><div class="teaching-reminder"><h4>让反馈成为下一次教学的起点</h4><p>查看每位学生的提交进度，给出具体建议。学生修改后生成新版本，等待你再次复核。</p><button class="subtle-link" @click="emit('navigate', 'students')">查看班级成员 <ArrowRight :size="15"/></button></div></section><aside><section class="panel activity-panel"><div class="section-heading"><h3>我的教学探索</h3><span class="muted small">近 7 天</span></div><ActivityChart :green="true" :dates="records.map(r => r.created_at)"/><p class="chart-caption">与教学助手的实际对话次数</p></section><div class="gentle-note"><Sparkles :size="19"/><p>教学助手的每条回复标明来源，<br>使用前请结合课程目标复核。</p></div></aside></div>
</template>
