<script setup lang="ts">
import { computed } from 'vue'
import { ArrowUpRight, ArrowRight, Sparkles, BookOpen, Bookmark, MessageCircle, Clock3, ChevronRight, Sigma, PencilLine } from 'lucide-vue-next'
import type { User, Conversation, Assignment } from '../shared/api'
import ActivityChart from '../shared/ActivityChart.vue'
const props = defineProps<{ user: User; records: Conversation[]; assignments: Assignment[] }>()
const emit = defineEmits<{ navigate: [page: string]; ask: [question: string] }>()
const todo = computed(() => props.assignments.filter(a => !a.submitted))
const completed = computed(() => props.assignments.filter(a => a.submitted).length)
</script>
<template>
  <div class="page-heading"><div><div class="eyebrow">A LITTLE PROGRESS, EVERY DAY</div><h1>你好，{{ user.name }} <span class="greeting-sun">☀</span></h1><p>不必一下子弄懂所有，从今天的一小步开始。</p></div><div class="date-chip"><Clock3 :size="15"/> {{ new Date().toLocaleDateString('zh-CN', { month: 'long', day: 'numeric', weekday: 'long' }) }}</div></div>
  <section class="hero-banner"><div class="hero-copy"><span class="hero-tag"><Sparkles :size="14"/> 你的专属学习伙伴</span><h2>有点难的高数，<br>我们一起<span>慢慢懂。</span></h2><p>从概念理解到解题思路，数伴陪你走好每一步。</p><button class="primary-button" @click="emit('navigate', 'agent')">和数伴聊一聊 <ArrowUpRight :size="18"/></button><small>当前为交互演示，真实 AI 能力即将接入</small></div><div class="hero-art" aria-hidden="true"><div class="art-ring"></div><div class="floating-math">f′(x) = <em>2x</em></div><svg viewBox="0 0 280 190"><path d="M30 156H257M83 179V13" stroke="#afa0d0" stroke-width="1"/><path d="M33 51Q135 261 248 32" stroke="#9579d3" stroke-width="3" fill="none"/><path d="M138 150L255 62" stroke="#d7b381" stroke-width="1.5" stroke-dasharray="5 5"/><circle cx="209" cy="96" r="6" fill="white" stroke="#9579d3" stroke-width="3"/><text x="243" y="175" fill="#a194b6" font-size="13">x</text></svg><div class="art-caption"><Sparkles :size="16"/> 每一次「为什么」，都是进步的开始。</div><span class="art-star">✧</span></div></section>
  <div class="stats-grid"><div class="stat-card"><span class="stat-icon lilac"><MessageCircle :size="20"/></span><div><span>与数伴的探索</span><strong>{{ records.length }}<small>次提问</small></strong></div><span class="stat-detail">真实记录</span></div><div class="stat-card"><span class="stat-icon peach"><Bookmark :size="20"/></span><div><span>我的复习收藏</span><strong>{{ records.filter(r => r.favorite).length }}<small>条记录</small></strong></div><button class="icon-button" aria-label="查看复习收藏" @click="emit('navigate', 'favorites')"><ArrowUpRight :size="19"/></button></div><div class="stat-card"><span class="stat-icon green"><PencilLine :size="20"/></span><div><span>已完成的作业</span><strong>{{ completed }}<small>/ {{ assignments.length }} 份</small></strong></div><span class="stat-detail">继续加油</span></div></div>
  <div class="dashboard-grid"><div class="dashboard-main"><section class="panel"><div class="section-heading"><h3>从这里，继续学习 <span class="section-sub">LEARNING PATH</span></h3><button class="subtle-link" @click="emit('navigate', 'courses')">全部章节 <ArrowRight :size="15"/></button></div><div class="course-grid"><button class="course-card" @click="emit('ask', '如何理解 sin(x)/x 在 x→0 时的极限？')"><div class="course-top"><span class="course-number">01</span><span class="small-pill">基础篇</span></div><div class="course-symbol">lim <small>x → a</small></div><h4>函数与极限</h4><p>从无限接近，理解确定的值</p><div class="course-bottom"><span>概念入门 · 例题探索</span><span class="circle-arrow"><ArrowUpRight :size="17"/></span></div></button><button class="course-card mint" @click="emit('ask', '用定义求 x² 的导数')"><div class="course-top"><span class="course-number">02</span><span class="small-pill">进阶篇</span></div><div class="course-symbol">f′(x)</div><h4>导数与微分</h4><p>看见变化，认识瞬时的力量</p><div class="course-bottom"><span>几何直觉 · 定义推导</span><span class="circle-arrow"><ArrowUpRight :size="17"/></span></div></button></div></section><section class="panel daily-thought"><div class="thought-icon"><Sigma :size="24"/></div><div><span class="section-kicker">今日一问</span><h3>函数在一点有极限，就一定在这一点有定义吗？</h3><p>先写下你的直觉，再用一个例子验证它。</p></div><button class="outline-button" @click="emit('ask', '函数在一点有极限，就一定在这一点有定义吗？')">想一想 <ArrowUpRight :size="15"/></button></section></div><aside class="dashboard-side"><section class="panel"><div class="section-heading"><h3>待办学习</h3><span class="count-badge">{{ todo.length }}</span></div><button v-for="a in todo.slice(0, 3)" :key="a.id" class="todo-item" @click="emit('navigate', 'assignments')"><span class="todo-circle"></span><div><strong>{{ a.title }}</strong><small>{{ a.due_date }} 截止</small></div><ChevronRight :size="15"/></button><p v-if="!todo.length" class="empty-small">今天的作业都完成啦，去探索新问题吧。</p><button class="subtle-link full-link" @click="emit('navigate', 'assignments')">查看我的作业 <ArrowRight :size="14"/></button></section><section class="panel activity-panel"><div class="section-heading"><h3>学习的足迹</h3><span class="muted small">近 7 天</span></div><ActivityChart :dates="records.map(r => r.created_at)"/><p class="chart-caption">每一个问题，都算数。<span>实际提问次数</span></p></section><div class="gentle-note"><BookOpen :size="18"/><p>学习不是一场竞赛，<br>理解比速度更重要。</p></div></aside></div>
</template>
